# Generated by Django 5.0.1 on 2026-05-26 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('no_hp', models.CharField(max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('penulis', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun_terbit', models.IntegerField()),
                ('kategori', models.CharField(max_length=100)),
                ('stok', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('status', models.CharField(choices=[('dipinjam', 'Dipinjam'), ('dikembalikan', 'Dikembalikan'), ('terlambat', 'Terlambat')], default='dipinjam', max_length=20)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anggota')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buku')),
            ],
        ),
        migrations.CreateModel(
            name='Pengembalian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dikembalikan', models.DateField()),
                ('denda', models.IntegerField(default=0)),
                ('peminjaman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.peminjaman')),
            ],
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIRecommendation',
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
