# Generated by Django 5.0.1 on 2026-05-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_anggota_buku_peminjaman_pengembalian_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anggota',
            options={'verbose_name': 'Anggota', 'verbose_name_plural': 'Anggota'},
        ),
        migrations.AlterModelOptions(
            name='buku',
            options={'verbose_name': 'Buku', 'verbose_name_plural': 'Buku'},
        ),
        migrations.AlterModelOptions(
            name='peminjaman',
            options={'verbose_name': 'Peminjaman', 'verbose_name_plural': 'Peminjaman'},
        ),
        migrations.AlterModelOptions(
            name='pengembalian',
            options={'verbose_name': 'Pengembalian', 'verbose_name_plural': 'Pengembalian'},
        ),
    ]
