# Generated by Django 5.0.1 on 2026-05-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aktivitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='sanksi_sampai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
